# 区级所有ID数据
AREA_DATA = [{'areaId': 22, 'areaName': '天河区',
              'region': [
                  {'areaId': 7784, 'regionName': '时尚天河'}, {'areaId': 7783, 'regionName': '天河城/体育西'},
                  {'areaId': 1380, 'regionName': '天河客运站'}, {'areaId': 717, 'regionName': '棠下'},
                  {'areaId': 714, 'regionName': '天河北/广州东站'}, {'areaId': 715, 'regionName': '岗顶/龙口'},
                  {'areaId': 716, 'regionName': '兴盛路/跑马场'}, {'areaId': 1164, 'regionName': '车陂/东圃'},
                  {'areaId': 1177, 'regionName': '燕岭/五山'}, {'areaId': 1490, 'regionName': '龙洞/岑村'},
                  {'areaId': 5199, 'regionName': '沙河/天平架/梅花园'}, {'areaId': 7782, 'regionName': '天河城/体育中心'},
                  {'areaId': 7791, 'regionName': '花城汇/高德置地'}, {'areaId': 9651, 'regionName': '小新塘'},
                  {'areaId': 13162, 'regionName': '员村'}, {'areaId': 13163, 'regionName': '华景新城'},
                  {'areaId': 13875, 'regionName': '正佳广场'}, {'areaId': 14319, 'regionName': '岑村/火炉山'},
                  {'areaId': 15110, 'regionName': '兴盛路/猎德'}, {'areaId': 15112, 'regionName': '珠江新城'},
                  {'areaId': 18528, 'regionName': '石牌/百脑汇'}, {'areaId': 18529, 'regionName': '天河公园/上社'},
                  {'areaId': 44734, 'regionName': '石牌/龙口'}, {'areaId': 45578, 'regionName': '黄村/奥体'}]},
             {'areaId': 23, 'areaName': '越秀区',
              'region': [
                  {'areaId': 1065, 'regionName': '中山二三路/东山口'}, {'areaId': 1066, 'regionName': '五羊新城'},
                  {'areaId': 721, 'regionName': '东风中路/越秀公园'}, {'areaId': 722, 'regionName': '中山六路'},
                  {'areaId': 723, 'regionName': '火车站/人民北路'}, {'areaId': 1276, 'regionName': '海珠广场'},
                  {'areaId': 719, 'regionName': '北京路商业区'}, {'areaId': 720, 'regionName': '沿江路/二沙岛'},
                  {'areaId': 1070, 'regionName': '麓湖公园'}, {'areaId': 7775, 'regionName': '东风东/杨箕'},
                  {'areaId': 19656, 'regionName': '瑶台'}, {'areaId': 19682, 'regionName': '建设六马路'},
                  {'areaId': 19683, 'regionName': '小北/淘金'}, {'areaId': 19684, 'regionName': '黄花岗'},
                  {'areaId': 19685, 'regionName': '环市东路/区庄'}, {'areaId': 19686, 'regionName': '区庄/动物园'},
                  {'areaId': 21631, 'regionName': '东山口/农林下路'}, {'areaId': 21642, 'regionName': '中华广场'}]},
             {'areaId': 24, 'areaName': '海珠区',
              'region': [
                  {'areaId': 1494, 'regionName': '江南西'}, {'areaId': 727, 'regionName': '滨江路沿线'},
                  {'areaId': 725, 'regionName': '江南大道沿线'}, {'areaId': 1179, 'regionName': '工业大道沿线'},
                  {'areaId': 726, 'regionName': '新港西路沿线'}, {'areaId': 1165, 'regionName': '客村/赤岗'},
                  {'areaId': 1178, 'regionName': '东晓南路沿线'}, {'areaId': 8961, 'regionName': '琶洲'}]},
             {'areaId': 25, 'areaName': '荔湾区',
              'region': [
                  {'areaId': 1067, 'regionName': '芳村'}, {'areaId': 730, 'regionName': '中山七八路'},
                  {'areaId': 1971, 'regionName': '恒宝广场'}, {'areaId': 731, 'regionName': '沙面'},
                  {'areaId': 729, 'regionName': '上下九商业区'}, {'areaId': 7540, 'regionName': '康王路'},
                  {'areaId': 7669, 'regionName': '西村/西场'}, {'areaId': 8925, 'regionName': '西城都荟'},
                  {'areaId': 23262, 'regionName': '滘口'}, {'areaId': 25088, 'regionName': '坦尾/河沙'}]},
             {'areaId': 26, 'areaName': '白云区',
              'region': [
                  {'areaId': 734, 'regionName': '机场路沿线'}, {'areaId': 1180, 'regionName': '白云大道沿线'},
                  {'areaId': 1493, 'regionName': '新市'}, {'areaId': 735, 'regionName': '三元里'},
                  {'areaId': 733, 'regionName': '广园新村'}, {'areaId': 1491, 'regionName': '同德围'},
                  {'areaId': 1181, 'regionName': '同和/京溪'}, {'areaId': 5193, 'regionName': '嘉禾/人和'},
                  {'areaId': 5196, 'regionName': '永泰'}, {'areaId': 7535, 'regionName': '嘉裕太阳城'},
                  {'areaId': 7536, 'regionName': '五号停机坪'}, {'areaId': 7537, 'regionName': '黄石'},
                  {'areaId': 7539, 'regionName': '万达广场'}, {'areaId': 7606, 'regionName': '罗冲围/金沙洲'},
                  {'areaId': 15984, 'regionName': '黄边'}, {'areaId': 16022, 'regionName': '石井'},
                  {'areaId': 16091, 'regionName': '钟落潭'}, {'areaId': 17078, 'regionName': '江高镇'},
                  {'areaId': 17256, 'regionName': '均禾'}, {'areaId': 18064, 'regionName': '太和镇'},
                  {'areaId': 25072, 'regionName': '白云绿地中心'}, {'areaId': 26659, 'regionName': '凯德广场'},
                  {'areaId': 27976, 'regionName': '白云国际机场'}, {'areaId': 37939, 'regionName': '嘉禾望岗'},
                  {'areaId': 40275, 'regionName': '龙归镇'}, {'areaId': 42033, 'regionName': '广外北校区'},
                  {'areaId': 46024, 'regionName': '百信广场'}]},
             {'areaId': 274, 'areaName': '番禺区',
              'region': [
                  {'areaId': 1182, 'regionName': '市桥'},
                  {'areaId': 9023, 'regionName': '市桥南'},
                  {'areaId': 1461, 'regionName': '番禺广场'},
                  {'areaId': 1184, 'regionName': '大学城'},
                  {'areaId': 9024, 'regionName': '沙湾镇'},
                  {'areaId': 1183, 'regionName': '大石'},
                  {'areaId': 5187, 'regionName': '洛溪'},
                  {'areaId': 7541, 'regionName': '长隆/南村'},
                  {'areaId': 7542, 'regionName': '钟村'},
                  {'areaId': 9276, 'regionName': '石碁'},
                  {'areaId': 14179, 'regionName': '石楼'},
                  {'areaId': 18905, 'regionName': '南浦'},
                  {'areaId': 23275, 'regionName': '广州南站'},
                  {'areaId': 40331, 'regionName': '厦滘'},
                  {'areaId': 44541, 'regionName': '长隆'}]},
             {'areaId': 737, 'areaName': '黄埔区',
              'region': [
                  {'areaId': 8029, 'regionName': '大沙地'}, {'areaId': 8030, 'regionName': '文冲'},
                  {'areaId': 8031, 'regionName': '鱼珠'}, {'areaId': 8032, 'regionName': '科学城/萝岗高德汇'},
                  {'areaId': 8033, 'regionName': '中心城'}, {'areaId': 8034, 'regionName': '开发区东区'},
                  {'areaId': 8035, 'regionName': '开发区西区'}, {'areaId': 8797, 'regionName': '生活区/南岗'},
                  {'areaId': 17692, 'regionName': '长洲岛'}, {'areaId': 22706, 'regionName': '萝岗万达广场'},
                  {'areaId': 38999, 'regionName': '联和联世广场'}, {'areaId': 44519, 'regionName': '万科东荟城'},
                  {'areaId': 44747, 'regionName': '夏园'}, {'areaId': 45367, 'regionName': '印象黄埔'},
                  {'areaId': 45579, 'regionName': '旺村/何棠下'}, {'areaId': 46370, 'regionName': '大沙东'}]},
             {'areaId': 738, 'areaName': '花都区',
              'region': [
                  {'areaId': 5882, 'regionName': '新世纪广场'}, {'areaId': 5883, 'regionName': '梯面'},
                  {'areaId': 5884, 'regionName': '花山'}, {'areaId': 5885, 'regionName': '炭步'},
                  {'areaId': 5886, 'regionName': '赤坭'}, {'areaId': 5887, 'regionName': '狮岭'},
                  {'areaId': 5888, 'regionName': '花东'}, {'areaId': 5889, 'regionName': '雅瑶'},
                  {'areaId': 13356, 'regionName': '北站/建设路'}, {'areaId': 13357, 'regionName': '花都广场/区政府'},
                  {'areaId': 13362, 'regionName': '来又来/大润发'}, {'areaId': 13715, 'regionName': '建设北路'},
                  {'areaId': 13904, 'regionName': '花都体育馆/花果山公园'}, {'areaId': 13905, 'regionName': '秀全公园'},
                  {'areaId': 14053, 'regionName': '喜立登饮食风情街'}, {'areaId': 16090, 'regionName': '白云国际机场'},
                  {'areaId': 23248, 'regionName': '莲塘'}, {'areaId': 36192, 'regionName': '雅居乐锦城/保利花城'},
                  {'areaId': 36194, 'regionName': '骏壹万邦'}, {'areaId': 39346, 'regionName': '马溪'},
                  {'areaId': 40276, 'regionName': '融创茂'}, {'areaId': 42780, 'regionName': '北站/太子步行街'}]},
             {'areaId': 739, 'areaName': '增城市',
              'region': [
                  {'areaId': 13071, 'regionName': '万达广场'}, {'areaId': 9181, 'regionName': '太阳城/凯旋门'},
                  {'areaId': 7718, 'regionName': '新塘大润发/新好景'}, {'areaId': 9178, 'regionName': '东汇城/人人乐'},
                  {'areaId': 9180, 'regionName': '荔城挂绿/泰富广场'}, {'areaId': 9504, 'regionName': '白水寨/派潭'},
                  {'areaId': 13070, 'regionName': '新塘广场'}, {'areaId': 13113, 'regionName': '凤凰城'},
                  {'areaId': 16723, 'regionName': '佰乐广场'}, {'areaId': 27311, 'regionName': '朱村镇'},
                  {'areaId': 27313, 'regionName': '中新镇'}, {'areaId': 27483, 'regionName': '沙埔镇'},
                  {'areaId': 27485, 'regionName': '永和镇'}, {'areaId': 37286, 'regionName': '合汇城广场'},
                  {'areaId': 38530, 'regionName': '挂绿广场/泰富广场'}, {'areaId': 39909, 'regionName': '敏捷锦绣广场'},
                  {'areaId': 40265, 'regionName': '新塘'}, {'areaId': 40266, 'regionName': '荔城'},
                  {'areaId': 40754, 'regionName': '新好景/大润发'}]},
             {'areaId': 740, 'areaName': '从化市',
              'region': [
                  {'areaId': 13069, 'regionName': '温泉镇'}, {'areaId': 13150, 'regionName': '街口/新世纪广场'},
                  {'areaId': 13153, 'regionName': '江埔'}, {'areaId': 13157, 'regionName': '欣荣宏广场'},
                  {'areaId': 15240, 'regionName': '商贸城'}, {'areaId': 15242, 'regionName': '碧水湾/碧水新村'},
                  {'areaId': 16273, 'regionName': '太平镇/太平商业街'}, {'areaId': 17630, 'regionName': '城郊/旺城'},
                  {'areaId': 23258, 'regionName': '溪头村'}, {'areaId': 25818, 'regionName': '鳌头/旗杆'},
                  {'areaId': 26381, 'regionName': '良口镇'}, {'areaId': 40192, 'regionName': '米埗小镇'}]},
             {'areaId': 1068, 'areaName': '南沙区',
              'region': [
                  {'areaId': 13845, 'regionName': '黄阁镇'}, {'areaId': 13848, 'regionName': '金洲商业街'},
                  {'areaId': 13850, 'regionName': '华汇广场'}, {'areaId': 13853, 'regionName': '板头'},
                  {'areaId': 15265, 'regionName': '东涌镇'}, {'areaId': 15267, 'regionName': '大岗'},
                  {'areaId': 15269, 'regionName': '珠江旧镇'}, {'areaId': 18624, 'regionName': '百万葵园/十九涌'},
                  {'areaId': 18626, 'regionName': '大涌'}, {'areaId': 18628, 'regionName': '榄核镇'},
                  {'areaId': 18630, 'regionName': '鱼窝头'}, {'areaId': 19803, 'regionName': '万顷沙镇'},
                  {'areaId': 25709, 'regionName': '南沙万达广场'}, {'areaId': 40194, 'regionName': '悠方购物公园'},
                  {'areaId': 45621, 'regionName': '金州商业区'}]}]

# 接口类目ID数据
CATEGORIES_ID_DATA = [{'name': '球类运动', 'id': 21305, 'subcategories': []},
                      {'name': '今日新单', 'id': 0, 'subcategories': []},
                      {'name': '猫眼电影', 'id': 99, 'subcategories': []},
                      {'name': '美食', 'id': 1,
                       'subcategories': [{'sub_name': '代金券', 'sub_Id': 393},
                                         {'sub_name': '甜点饮品', 'sub_Id': 11}, {'sub_name': '生日蛋糕', 'sub_Id': 20097},
                                         {'sub_name': '火锅', 'sub_Id': 17}, {'sub_name': '自助餐', 'sub_Id': 40},
                                         {'sub_name': '小吃快餐', 'sub_Id': 36}, {'sub_name': '日韩料理', 'sub_Id': 28},
                                         {'sub_name': '西餐', 'sub_Id': 35}, {'sub_name': '聚餐宴请', 'sub_Id': 395},
                                         {'sub_name': '烧烤烤肉', 'sub_Id': 54}, {'sub_name': '川湘菜', 'sub_Id': 55},
                                         {'sub_name': '江浙菜', 'sub_Id': 56}, {'sub_name': '小龙虾', 'sub_Id': 528},
                                         {'sub_name': '东北菜', 'sub_Id': 20003}, {'sub_name': '香锅烤鱼', 'sub_Id': 20004},
                                         {'sub_name': '粤菜', 'sub_Id': 57}, {'sub_name': '中式烧烤/烤串', 'sub_Id': 400},
                                         {'sub_name': '西北菜', 'sub_Id': 58}, {'sub_name': '咖啡酒吧', 'sub_Id': 41},
                                         {'sub_name': '徽菜', 'sub_Id': 526}, {'sub_name': '京菜鲁菜', 'sub_Id': 59},
                                         {'sub_name': '云贵菜', 'sub_Id': 60}, {'sub_name': '东南亚菜', 'sub_Id': 62},
                                         {'sub_name': '海鲜', 'sub_Id': 63}, {'sub_name': '素食', 'sub_Id': 217},
                                         {'sub_name': '台湾/客家菜', 'sub_Id': 227}, {'sub_name': '创意菜', 'sub_Id': 228},
                                         {'sub_name': '汤/粥/炖菜', 'sub_Id': 229}, {'sub_name': '蒙餐', 'sub_Id': 232},
                                         {'sub_name': '新疆菜', 'sub_Id': 233}, {'sub_name': '其他美食', 'sub_Id': 24}]},

                      {'name': '周边游', 'id': 195, 'subcategories': [
                          {'sub_name': '温泉', 'sub_Id': 304},
                          {'sub_name': '景点', 'sub_Id': 296},
                          {'sub_name': '主题公园', 'sub_Id': 297}, {'sub_name': '水上乐园', 'sub_Id': 298},
                          {'sub_name': '动植物园', 'sub_Id': 299},
                          {'sub_name': '海洋馆', 'sub_Id': 300}, {'sub_name': '展览馆', 'sub_Id': 301},
                          {'sub_name': '游船', 'sub_Id': 302},
                          {'sub_name': '高空观景', 'sub_Id': 303}, {'sub_name': '滑雪', 'sub_Id': 307},
                          {'sub_name': '真人CS', 'sub_Id': 305},
                          {'sub_name': '漂流', 'sub_Id': 308}, {'sub_name': '租车/单车', 'sub_Id': 306},
                          {'sub_name': '其他游玩', 'sub_Id': 310},
                          {'sub_name': '农家乐', 'sub_Id': 309}]},
                      {'name': '休闲娱乐', 'id': 2,
                       'subcategories': [
                           {'sub_name': '足疗/按摩', 'sub_Id': 52},
                           {'sub_name': '洗浴/汗蒸', 'sub_Id': 112},
                           {'sub_name': 'KTV', 'sub_Id': 10},
                           {'sub_name': '酒吧', 'sub_Id': 234},
                           {'sub_name': '电玩/游戏厅', 'sub_Id': 38},
                           {'sub_name': '密室逃脱', 'sub_Id': 230},
                           {'sub_name': '运动健身', 'sub_Id': 39},
                           {'sub_name': '私人影院', 'sub_Id': 20104},
                           {'sub_name': 'DIY手工坊', 'sub_Id': 218},
                           {'sub_name': '网吧网咖', 'sub_Id': 20770},
                           {'sub_name': '棋牌室', 'sub_Id': 20776},
                           {'sub_name': '轰趴馆', 'sub_Id': 20773},
                           {'sub_name': '桌游', 'sub_Id': 20777},
                           {'sub_name': '采摘/农家乐', 'sub_Id': 516},
                           {'sub_name': '茶馆', 'sub_Id': 20772},
                           {'sub_name': '真人CS', 'sub_Id': 219},
                           {'sub_name': 'VR', 'sub_Id': 20779},
                           {'sub_name': '演出赛事', 'sub_Id': 37},
                           {'sub_name': '更多休闲娱乐', 'sub_Id': 26},
                           {'sub_name': '温泉', 'sub_Id': 34}]},
                      {'name': '购物', 'id': 4,
                       'subcategories': [{'sub_name': '食品', 'sub_Id': 178},
                                         {'sub_name': '家居日用', 'sub_Id': 177}, {'sub_name': '女装', 'sub_Id': 271},
                                         {'sub_name': '男装', 'sub_Id': 270}, {'sub_name': '内衣', 'sub_Id': 272},
                                         {'sub_name': '美妆', 'sub_Id': 179}, {'sub_name': '家纺', 'sub_Id': 269},
                                         {'sub_name': '鞋靴', 'sub_Id': 273}, {'sub_name': '箱包皮具', 'sub_Id': 183},
                                         {'sub_name': '母婴玩具', 'sub_Id': 181}, {'sub_name': '数码电器', 'sub_Id': 180},
                                         {'sub_name': '配饰手表', 'sub_Id': 186}, {'sub_name': '家具家装', 'sub_Id': 316},
                                         {'sub_name': '运动户外', 'sub_Id': 184}, {'sub_name': '汽车用品', 'sub_Id': 358},
                                         {'sub_name': '本地购物', 'sub_Id': 188}]},
                      {'name': '度假出行', 'id': 20513,
                       'subcategories': [
                           {'sub_name': '境外游',
                            'sub_Id': 161},
                           {'sub_name': '火车票',
                            'sub_Id': 20066},
                           {'sub_name': '景点门票',
                            'sub_Id': 162}]},
                      {'name': '宴会', 'id': 20375,
                       'subcategories': [{'sub_name': '一站式婚礼会馆', 'sub_Id': 20377},
                                         {'sub_name': '酒店宴会厅', 'sub_Id': 20378},
                                         {'sub_name': '特色餐饮', 'sub_Id': 20379}]},
                      {'name': '时尚购', 'id': 20383,
                       'subcategories': [
                           {
                               'sub_name': '本地购物',
                               'sub_Id': 20384},
                           {
                               'sub_name': '服饰鞋包',
                               'sub_Id': 20385},
                           {'sub_name': '配镜',
                            'sub_Id': 20386},
                           {'sub_name': '鲜花',
                            'sub_Id': 20387},
                           {
                               'sub_name': '数码家电',
                               'sub_Id': 20642},
                           {
                               'sub_name': '超市/便利店',
                               'sub_Id': 20704},
                           {
                               'sub_name': '珠宝饰品',
                               'sub_Id': 20764}]},
                      {'name': '丽人', 'id': 22,
                       'subcategories': [{'sub_name': '美发', 'sub_Id': 74},
                                         {'sub_name': '美容美体', 'sub_Id': 76}, {'sub_name': '美甲美睫', 'sub_Id': 75},
                                         {'sub_name': '瑜伽舞蹈', 'sub_Id': 220}, {'sub_name': '瘦身纤体', 'sub_Id': 20422},
                                         {'sub_name': '韩式定妆', 'sub_Id': 20419}, {'sub_name': '祛痘', 'sub_Id': 20421},
                                         {'sub_name': '纹身', 'sub_Id': 20420}, {'sub_name': '整形', 'sub_Id': 20423},
                                         {'sub_name': '化妆品', 'sub_Id': 20418}]},
                      {'name': '旅游', 'id': 78,
                       'subcategories': [

                           {'sub_name': '跟团游',
                            'sub_Id': 338},
                           {'sub_name': '国内游',
                            'sub_Id': 226},
                           {'sub_name': '用车', 'sub_Id': 354},
                           {'sub_name': '自由行',
                            'sub_Id': 339},
                           {'sub_name': '签证',
                            'sub_Id': 343}]},
                      {'name': '生活服务', 'id': 3,
                       'subcategories': [{'sub_name': '汽车服务', 'sub_Id': 20128},
                                         {'sub_name': '其他生活', 'sub_Id': 25}, {'sub_name': '证件照', 'sub_Id': 20196},
                                         {'sub_name': '配镜', 'sub_Id': 68}, {'sub_name': '搬家', 'sub_Id': 20454},
                                         {'sub_name': '体检/齿科', 'sub_Id': 32}, {'sub_name': '家政洗衣', 'sub_Id': 66},
                                         {'sub_name': '鲜花', 'sub_Id': 65}, {'sub_name': '照片冲印', 'sub_Id': 221},
                                         {'sub_name': '商场购物卡', 'sub_Id': 235}, {'sub_name': '充值服务', 'sub_Id': 20111},
                                         {'sub_name': '健康服务', 'sub_Id': 20283}, {'sub_name': '开锁', 'sub_Id': 20457},
                                         {'sub_name': '培训课程', 'sub_Id': 19}, {'sub_name': '跑腿代购', 'sub_Id': 20870},
                                         {'sub_name': '服饰鞋包', 'sub_Id': 20057}, {'sub_name': '母婴亲子', 'sub_Id': 67},
                                         {'sub_name': '婚庆', 'sub_Id': 20093}, {'sub_name': '电器数码', 'sub_Id': 20056}]},
                      {'name': '运动健身', 'id': 20252,
                       'subcategories': [{'sub_name': '游泳/水上运动', 'sub_Id': 20256},
                                         {'sub_name': '健身房/体操房', 'sub_Id': 20253}, {'sub_name': '羽毛球', 'sub_Id': 20257},
                                         {'sub_name': '台球', 'sub_Id': 20262}, {'sub_name': '武术', 'sub_Id': 20266},
                                         {'sub_name': '保龄球', 'sub_Id': 20261}, {'sub_name': '高尔夫', 'sub_Id': 20260},
                                         {'sub_name': '篮球', 'sub_Id': 20258}, {'sub_name': '滑冰', 'sub_Id': 20268},
                                         {'sub_name': '射箭', 'sub_Id': 20270}, {'sub_name': '网球', 'sub_Id': 20259},
                                         {'sub_name': '骑马', 'sub_Id': 20267}, {'sub_name': '足球', 'sub_Id': 20264},
                                         {'sub_name': '乒乓球', 'sub_Id': 20265}, {'sub_name': '壁球', 'sub_Id': 20269},
                                         {'sub_name': '舞蹈', 'sub_Id': 20255}, {'sub_name': '瑜伽', 'sub_Id': 20254},
                                         {'sub_name': '综合体育场馆', 'sub_Id': 20263},
                                         {'sub_name': '其他运动', 'sub_Id': 20271}]},
                      {'name': '母婴亲子', 'id': 20007,
                       'subcategories': [
                           {
                               'sub_name': '儿童乐园',
                               'sub_Id': 20108},
                           {
                               'sub_name': '婴儿游泳',
                               'sub_Id': 20514},
                           {
                               'sub_name': '其它亲子游乐',
                               'sub_Id': 20782},
                           {
                               'sub_name': '儿童摄影',
                               'sub_Id': 20048},
                           {
                               'sub_name': '孕妇写真',
                               'sub_Id': 20515},
                           {
                               'sub_name': '母婴护理',
                               'sub_Id': 20042},
                           {
                               'sub_name': '幼儿教育',
                               'sub_Id': 20045},
                           {
                               'sub_name': '更多亲子服务',
                               'sub_Id': 20171},
                           {
                               'sub_name': '亲子购物',
                               'sub_Id': 20517},
                           {
                               'sub_name': '宝宝派对',
                               'sub_Id': 20785},
                           {
                               'sub_name': '手工DIY',
                               'sub_Id': 20049},
                           {
                               'sub_name': '其他亲子',
                               'sub_Id': 20786},
                           {
                               'sub_name': '儿童话剧',
                               'sub_Id': 20051},
                           {
                               'sub_name': '科普场馆',
                               'sub_Id': 20044},
                           {
                               'sub_name': '采摘/农家乐',
                               'sub_Id': 20050},
                           {
                               'sub_name': '主题公园',
                               'sub_Id': 20043}]},
                      {'name': '宠物', 'id': 20691,
                       'subcategories': [{'sub_name': '宠物店', 'sub_Id': 20692},
                                         {'sub_name': '宠物医院', 'sub_Id': 20693}]},
                      {'name': '汽车服务', 'id': 27,
                       'subcategories': [

                           {'sub_name': '洗车',
                            'sub_Id': 20115},
                           {'sub_name': '汽车美容',
                            'sub_Id': 20120},
                           {'sub_name': '维修保养',
                            'sub_Id': 20118},
                           {'sub_name': '打蜡',
                            'sub_Id': 20302},
                           {'sub_name': '镀晶镀膜',
                            'sub_Id': 20300},
                           {'sub_name': '小保养',
                            'sub_Id': 20299},
                           {'sub_name': '汽车贴膜',
                            'sub_Id': 20301},
                           {'sub_name': '内饰清洁',
                            'sub_Id': 20382},
                           {'sub_name': '租车',
                            'sub_Id': 20116},
                           {'sub_name': '汽车改装',
                            'sub_Id': 20767},
                           {'sub_name': '汽车配件',
                            'sub_Id': 20768},
                           {'sub_name': '汽车陪练',
                            'sub_Id': 20121},
                           {'sub_name': '4S',
                            'sub_Id': 20163},
                           {'sub_name': '汽车用品',
                            'sub_Id': 20135},
                           {'sub_name': '停车场',
                            'sub_Id': 20161},
                           {'sub_name': '更多服务',
                            'sub_Id': 20164}]},
                      {'name': '摄影写真', 'id': 29,
                       'subcategories': [{'sub_name': '婚纱摄影', 'sub_Id': 396},
                                         {'sub_name': '个性写真', 'sub_Id': 397}, {'sub_name': '亲子摄影', 'sub_Id': 398},
                                         {'sub_name': '其他摄影', 'sub_Id': 399}]},
                      {'name': '结婚', 'id': 20178,
                       'subcategories': [
                           {'sub_name': '婚纱礼服',
                            'sub_Id': 20199},
                           {'sub_name': '西服定制',
                            'sub_Id': 20200},
                           {'sub_name': '婚庆公司',
                            'sub_Id': 20201},
                           {'sub_name': '婚戒首饰',
                            'sub_Id': 20202},
                           {'sub_name': '婚纱摄影',
                            'sub_Id': 20198},
                           {'sub_name': '个性写真',
                            'sub_Id': 20641},
                           {'sub_name': '婚礼小礼品',
                            'sub_Id': 20203},
                           {'sub_name': '婚车租赁',
                            'sub_Id': 20204},
                           {'sub_name': '彩妆造型',
                            'sub_Id': 20205},
                           {'sub_name': '司仪主持',
                            'sub_Id': 20206},
                           {'sub_name': '婚礼跟拍',
                            'sub_Id': 20207}, {
                               'sub_name': '更多婚礼服务',
                               'sub_Id': 20208},
                           {'sub_name': '婚宴',
                            'sub_Id': 20210},
                           {'sub_name': '旅拍婚照',
                            'sub_Id': 20303},
                           {'sub_name': '婚房装修',
                            'sub_Id': 20211}]},
                      {'name': '医疗', 'id': 20274,
                       'subcategories': [{'sub_name': '医院', 'sub_Id': 20275},
                                         {'sub_name': '齿科口腔', 'sub_Id': 20276}, {'sub_name': '体检中心', 'sub_Id': 20277},
                                         {'sub_name': '药店', 'sub_Id': 20278}]},
                      {'name': '家装', 'id': 20179,
                       'subcategories': [
                           {'sub_name': '装修设计',
                            'sub_Id': 20180},
                           {'sub_name': '家用电器',
                            'sub_Id': 20183},
                           {'sub_name': '家装卖场',
                            'sub_Id': 20184},
                           {'sub_name': '装修建材',
                            'sub_Id': 20182},
                           {'sub_name': '家具家居',
                            'sub_Id': 20771}]},
                      {'name': '出境游', 'id': 20485,
                       'subcategories': [{'sub_name': '美食', 'sub_Id': 20490},
                                         {'sub_name': '当地玩乐', 'sub_Id': 20486}, {'sub_name': '交通/用车', 'sub_Id': 20491},
                                         {'sub_name': '自由行', 'sub_Id': 20525},
                                         {'sub_name': 'Wi-Fi/电话卡', 'sub_Id': 20528}]},
                      {'name': '学习培训', 'id': 20285,
                       'subcategories': [

                           {'sub_name': '外语培训',
                            'sub_Id': 20286},
                           {'sub_name': '音乐培训',
                            'sub_Id': 20287},
                           {'sub_name': '美术培训',
                            'sub_Id': 20288},
                           {'sub_name': '驾校',
                            'sub_Id': 20629},
                           {'sub_name': '教育院校',
                            'sub_Id': 20289},
                           {'sub_name': '职业技术',
                            'sub_Id': 20291},
                           {'sub_name': '升学辅导',
                            'sub_Id': 20292},
                           {'sub_name': '留学',
                            'sub_Id': 20293},
                           {'sub_name': '兴趣生活',
                            'sub_Id': 20294},
                           {'sub_name': '更多教育培训',
                            'sub_Id': 20290}]},
                      {'name': '抽奖', 'id': 5,
                       'subcategories': [{'sub_name': '美梦成真', 'sub_Id': 203},
                                         {'sub_name': '霸王餐', 'sub_Id': 204}, {'sub_name': 'free游', 'sub_Id': 313},
                                         {'sub_name': '一元夺宝', 'sub_Id': 363}]}]

# 白云区area
BAIYUN_AREA = ["江高镇", "永泰", "白云区", "白云国际机场", "白云大道沿线",
               "白云绿地中心",
               "百信广场",
               "石井",
               "罗冲围/金沙洲",
               "钟落潭",
               "黄石",
               "黄边",
               "龙归镇", "太和镇",
               "广园新村", "广外北校区",
               "新市", "机场路沿线",
               "万达广场",
               "三元里",
               "五号停机坪",
               "凯德广场",
               "北站",
               "同和/京溪",
               "同德围",
               "嘉禾/人和",
               "嘉禾望岗",
               "嘉裕太阳城",
               "均禾"
               ]


